---
sidebar: sidebar 
permalink: use/task-replicate-data.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: Dopo aver creato o individuato un sistema FSx for ONTAP in NetApp Console, è possibile gestire il file system e utilizzare i servizi dati NetApp che forniscono funzionalità quali backup e ripristino. 
---
= Replica i dati FSx for ONTAP nella NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Replica i dati per proteggerli dalla perdita se la regione in cui risiedono i tuoi dati subisce un disastro. La replica dei dati è supportata tra file system FSx for ONTAP e sistemi ONTAP on-premises o Cloud Volumes ONTAP.

.Informazioni su questo compito
Questa operazione crea una relazione di replica per i volumi di origine in un file system FSx for ONTAP, un sistema ONTAP on-premises o un sistema Cloud Volumes ONTAP.

I volumi replicati nel file system di destinazione sono volumi di protezione dati (DP) e seguono il formato di denominazione: `{OriginalVolumeName}_copy`.

.Prima di iniziare
Prima di iniziare, tieni presente quanto segue.

* Per replicare i dati tra FSx for ONTAP e ONTAP on-premises o Cloud Volumes ONTAP, è necessario selezionare un agente Console con connettività al file system oppure inserire il file system per associare un collegamento. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Scopri come usare i link"^]
* La replica non è supportata per i volumi in uno stato diverso da disponibile, creato o configurato in modo errato e quando la versione di ONTAP non è compatibile.


.Passi
. Dalla pagina Systems della NetApp Console, trascina il file system FSx for ONTAP di origine, il sistema ONTAP on-premises o il sistema Cloud Volumes ONTAP sopra il file system FSx for ONTAP di destinazione e seleziona *Replication*.
. Nella pagina Crea replica, seleziona i volumi di origine da replicare, quindi *Avanti*.
. In Destinazione replica, fornire quanto segue:
+
.. *Nome destinazione*: hai applicato il nome destinazione quando hai trascinato e rilasciato il sistema storage di origine sul sistema di destinazione nella pagina Console Systems.
.. *Caso d'uso*: selezionare uno dei seguenti casi d'uso per la replica.  A seconda del caso d'uso selezionato, Workload Factory compila il modulo con i valori consigliati in conformità con le best practice.  È possibile accettare i valori consigliati o apportare modifiche durante la compilazione del modulo.
+
*** Migrazione: trasferisce i dati al file system FSx for ONTAP di destinazione
*** Ripristino di emergenza a caldo: garantisce elevata disponibilità e rapido ripristino di emergenza per carichi di lavoro critici
*** Ripristino di emergenza a freddo o in archivio:
+
**** Ripristino di emergenza a freddo: utilizza obiettivi di tempo di ripristino (RTO) e oggetti di punto di ripristino (RPO) più lunghi per ridurre i costi
**** Archivio: replica i dati per l'archiviazione a lungo termine e la conformità


*** Altro
+
Inoltre, la selezione del caso d'uso determina la politica di replicazione, o politica SnapMirror (ONTAP).  I termini utilizzati per descrivere le politiche di replicazione provengono dalink:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["Documentazione ONTAP 9"^] .

+
**** Per la migrazione e altro, la politica di replicazione si chiama _MirrorAllSnapshots_.  _MirrorAllSnapshots_ è una policy asincrona per il mirroring di tutti gli snapshot e dell'ultimo file system attivo.
**** Per il disaster recovery a caldo, a freddo o tramite archivio, la policy di replica è denominata _MirrorAndVault_.  _MirrorAndVault_ è una policy asincrona e di vault per il mirroring del file system attivo più recente e degli snapshot giornalieri e settimanali.
+
Per tutti i casi d'uso, se si abilitano gli snapshot per la conservazione a lungo termine, il criterio di replica predefinito è _MirrorAndVault_.





.. *FSx for ONTAP file system*: seleziona credenziali, regione e nome del FSx for ONTAP file system per il file system di destinazione FSx for ONTAP.
.. *Nome VM di archiviazione*: seleziona la VM di archiviazione dal menu a discesa.  La VM di archiviazione selezionata è la destinazione per tutti i volumi selezionati in questa relazione di replica.
.. *Nome volume*: il nome del volume di destinazione viene generato automaticamente con il seguente formato `{OriginalVolumeName}_copy` .  È possibile utilizzare il nome del volume generato automaticamente oppure immettere un altro nome del volume.
.. *Criterio di suddivisione in livelli*: selezionare il criterio di suddivisione in livelli per i dati archiviati nel volume di destinazione.  Per impostazione predefinita, la politica di suddivisione in livelli è quella consigliata per il caso d'uso selezionato.
+
_Bilanciato (Automatico)_ è il criterio di suddivisione in livelli predefinito quando si crea un volume utilizzando la console Workload Factory.  Per ulteriori informazioni sulle politiche di suddivisione in livelli del volume, fare riferimento alink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacità di archiviazione del volume"^] nella documentazione di AWS FSx per NetApp ONTAP .  Si noti che Workload Factory utilizza nomi basati sui casi d'uso nella console Workload Factory per i criteri di suddivisione in livelli e include i nomi dei criteri di suddivisione in livelli FSx for ONTAP tra parentesi.

+
Se hai selezionato il caso d'uso di migrazione, Workload Factory sceglie automaticamente di copiare la policy di suddivisione in livelli del volume di origine nel volume di destinazione.  È possibile deselezionare la copia del criterio di suddivisione in livelli e selezionare un criterio di suddivisione in livelli che si applichi al volume selezionato per la replica.

.. *Velocità di trasferimento massima*: seleziona *Limitata* e inserisci il limite massimo di trasferimento in MB/s.  In alternativa, seleziona *Illimitato*.
+
Senza limiti, le prestazioni della rete e delle applicazioni potrebbero diminuire.  In alternativa, consigliamo una velocità di trasferimento illimitata per FSx per i file system ONTAP per carichi di lavoro critici, ad esempio quelli utilizzati principalmente per il ripristino di emergenza.



. Nelle impostazioni di replica, specificare quanto segue:
+
.. *Intervallo di replica*: seleziona la frequenza con cui gli snapshot vengono trasferiti dal volume di origine al volume di destinazione.
.. *Conservazione a lungo termine*: facoltativamente, abilitare gli snapshot per la conservazione a lungo termine.  La conservazione a lungo termine consente ai servizi aziendali di continuare a funzionare anche in caso di guasto completo del sito, supportando il failover delle applicazioni in modo trasparente utilizzando una copia secondaria.
+
Le repliche senza conservazione a lungo termine utilizzano il criterio _MirrorAllSnapshots_.  L'abilitazione della conservazione a lungo termine assegna il criterio _MirrorAndVault_ alla replica.

+
Se si abilita la conservazione a lungo termine, selezionare un criterio esistente o crearne uno nuovo per definire gli snapshot da replicare e il numero da conservare.

+

NOTE: Per una conservazione a lungo termine è necessario che le etichette di origine e di destinazione corrispondano.  Se lo desideri, Workload Factory può creare per te le etichette mancanti.

+
*** *Scegli una polizza esistente*: seleziona una polizza esistente dal menu a discesa.
*** *Crea una nuova policy*: inserisci un *nome policy*.


.. *Snapshot immutabili*: Facoltativo.  Selezionare *Abilita snapshot immutabili* per impedire che gli snapshot acquisiti in questo criterio vengano eliminati durante il periodo di conservazione.
+
*** Imposta il *Periodo di conservazione* in numero di ore, giorni, mesi o anni.
*** *Criteri di snapshot*: nella tabella, seleziona la frequenza dei criteri di snapshot e il numero di copie da conservare.  È possibile selezionare più di un criterio snapshot.


.. *Punto di accesso S3*: facoltativamente, collega un punto di accesso S3 per accedere ai dati del file system FSx for ONTAP residenti su volumi NFS o SMB/CIFS tramite le API AWS S3. È supportato solo il tipo di accesso ai file. Fornire i seguenti dettagli:
+
*** *Nome punto di accesso S3*: Inserisci il nome del punto di accesso S3.
*** *Utente*: Seleziona un utente esistente con accesso al volume o crea un nuovo utente.
*** *Tipo di utente*: seleziona *UNIX* o *Windows* come tipo di utente.
*** *Configurazione di rete*: seleziona *Internet* o *Virtual private cloud (VPC)*. Il tipo di rete scelto determina se il punto di accesso è accessibile da Internet o limitato a una VPC specifica.
*** *Abilita metadati*: l'abilitazione dei metadati crea una tabella S3 contenente tutti gli oggetti accessibili dal punto di accesso S3, che puoi utilizzare per auditing, governance, analisi automatica e ottimizzazione. L'abilitazione dei metadati comporta costi AWS aggiuntivi. Consulta link:https://aws.amazon.com/s3/pricing/["Documentazione sui prezzi di Amazon S3"^] per ulteriori informazioni.


.. *Tag del punto di accesso S3*: Facoltativamente, puoi aggiungere fino a 50 tag.




. Seleziona *Crea*.

