---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, NetApp Console 
summary: Dopo aver creato o individuato un sistema FSx for ONTAP in NetApp Console, è possibile gestire il file system e utilizzare i servizi dati NetApp che forniscono funzionalità quali backup e ripristino. 
---
= Gestire un file system FSx per ONTAP nella NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dopo aver creato o individuato un sistema FSx for ONTAP nella NetApp Console, è possibile gestire il file system creando volumi, gestendo VM di storage, proteggendo i dati e amministrando il file system.  La Console consente inoltre di utilizzare servizi dati che offrono funzionalità quali backup e ripristino, classificazione dei dati, sincronizzazione dei dati e altro ancora.



== Gestire un file system utilizzando NetApp Workload Factory

Quando si apre un sistema FSx for ONTAP dalla pagina Sistemi della NetApp Console, si viene indirizzati a NetApp Workload Factory. NetApp Workload Factory è un servizio intelligente di ottimizzazione e automazione che utilizza le migliori pratiche del settore per pianificare, predisporre e gestire i carichi di lavoro principali utilizzando Amazon FSx for NetApp ONTAP.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Scopri come gestire un file system utilizzando NetApp Workload Factory"^]



== Gestire un file system utilizzando ONTAP System Manager

È possibile gestire un file system FSx per ONTAP direttamente dalla Console utilizzando l'interfaccia ONTAP System Manager. Per utilizzare System Manager è necessario un agente Console o un collegamento AWS Lambda.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Scopri come usare i link"^]



== Gestisci un file system utilizzando Amazon CloudFormation

È possibile effettuare il provisioning e gestire le risorse del file system FSx for ONTAP (volumi, condivisioni CIFS, policy di esportazione e altro) utilizzando Amazon CloudFormation.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["Repository GitHub del provider NetApp CloudFormation FSx per ONTAP"^]



== Utilizzare i servizi dati NetApp con un file system

Utilizza i servizi dati NetApp con i tuoi file system FSx for ONTAP per eseguire il backup e il ripristino dei dati, trasferire e sincronizzare i dati, analizzare e classificare i dati, replicare i dati e velocizzare l'accesso o scaricare il traffico.



=== Esegui il backup e il ripristino dei tuoi dati

NetApp Backup and Recovery offre una protezione dei dati efficiente, sicura e conveniente per i dati, i database e le macchine virtuali NetApp ONTAP , sia in locale che nel cloud.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Inizia con NetApp Backup and Recovery"^]



=== Trasferisci e sincronizza i dati

NetApp Copy and Sync è un servizio di replicazione e sincronizzazione cloud per il trasferimento di dati NAS tra archivi di oggetti locali e cloud.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["Inizia con NetApp Copy and Sync"^]



=== Scansiona e classifica i tuoi dati

NetApp Data Classification consente di analizzare e classificare i dati nel multicloud ibrido della tua organizzazione.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["Inizia con NetApp Data Classification"^]



=== Accelerare l'accesso o scaricare il traffico

NetApp Volume Caching fornisce un volume persistente e scrivibile in una posizione remota.  È possibile utilizzare la memorizzazione nella cache dei volumi per velocizzare l'accesso ai dati o per scaricare il traffico dai volumi a cui si accede più frequentemente.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["Introduzione alla memorizzazione nella NetApp Volume Caching"^]
