---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: Dopo aver creato o individuato un sistema FSx for ONTAP in NetApp Console, è possibile gestire il file system e utilizzare i servizi dati NetApp che forniscono funzionalità quali backup e ripristino. 
---
= Gestire un file system FSx per ONTAP nella NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dopo aver creato o individuato un sistema FSx for ONTAP nella NetApp Console, è possibile gestire il file system creando volumi, gestendo VM di storage, proteggendo i dati e amministrando il file system.  La Console consente inoltre di utilizzare servizi dati che offrono funzionalità quali backup e ripristino, classificazione dei dati, sincronizzazione dei dati e altro ancora.



== Gestisci un file system utilizzando NetApp Workloads

Quando si apre un sistema FSx for ONTAP dalla pagina Sistemi NetApp Console , si accede a NetApp Workloads.  Workloads è un servizio di ottimizzazione e automazione intelligente che utilizza le migliori pratiche del settore per progettare, configurare e gestire carichi di lavoro chiave utilizzando Amazon FSx for NetApp ONTAP.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Scopri come gestire un file system utilizzando NetApp Workloads"^]



== Gestire un file system utilizzando ONTAP System Manager

È possibile gestire un file system FSx per ONTAP direttamente dalla Console utilizzando l'interfaccia ONTAP System Manager. Per utilizzare System Manager è necessario un agente Console o un collegamento AWS Lambda.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Scopri come usare i link"^]



== Gestisci un file system utilizzando Amazon CloudFormation

È possibile effettuare il provisioning e gestire le risorse del file system FSx for ONTAP (volumi, condivisioni CIFS, policy di esportazione e altro) utilizzando Amazon CloudFormation.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["Repository GitHub del provider NetApp CloudFormation FSx per ONTAP"^]



== Utilizzare i servizi dati NetApp con un file system

Utilizza i servizi dati NetApp con i tuoi file system FSx for ONTAP per eseguire il backup e il ripristino dei dati, trasferire e sincronizzare i dati, analizzare e classificare i dati, replicare i dati e velocizzare l'accesso o scaricare il traffico.



=== Esegui il backup e il ripristino dei tuoi dati

NetApp Backup and Recovery offre una protezione dei dati efficiente, sicura e conveniente per i dati, i database e le macchine virtuali NetApp ONTAP , sia in locale che nel cloud.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Inizia con NetApp Backup and Recovery"^]



=== Trasferisci e sincronizza i dati

NetApp Copy and Sync è un servizio di replicazione e sincronizzazione cloud per il trasferimento di dati NAS tra archivi di oggetti locali e cloud.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["Inizia con NetApp Copy and Sync"^]



=== Scansiona e classifica i tuoi dati

NetApp Data Classification consente di analizzare e classificare i dati nel multicloud ibrido della tua organizzazione.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["Inizia con NetApp Data Classification"^]



=== Replicare i dati

Replicare i dati per supportare il backup e il ripristino di emergenza. La replica dei dati tra un file system FSx for ONTAP e Cloud Volumes ONTAP può essere eseguita utilizzando NetApp Replication. La replica consente di replicare i dati tra i sistemi di archiviazione ONTAP per supportare il backup e il ripristino di emergenza sul cloud o tra cloud.

link:https://docs.netapp.com/us-en/data-services-replication/task-replicating-data.html["Inizia con NetApp Replication"^]

La replica dei dati tra due file system FSx for ONTAP e tra un sistema ONTAP locale e un file system FSx for ONTAP è possibile dalla pagina dei sistemi NetApp Console .

.Prima di iniziare
Prima di iniziare, tieni presente quanto segue.

* Per replicare i dati tra due file system FSx for ONTAP o tra un sistema ONTAP locale e un file system FSx for ONTAP , è necessario selezionare un agente Console con connettività al file system oppure accedere al file system per associare un collegamento.
* La replica non è supportata per i volumi in uno stato diverso da disponibile, creato o configurato in modo errato e quando la versione ONTAP non è compatibile.


.Passi
. Dalla pagina Sistemi NetApp Console , trascinare il file system FSx for ONTAP di origine o il sistema ONTAP locale sopra il file system FSx for ONTAP di destinazione e selezionare *Replica*.
. Nella pagina Crea replica, seleziona i volumi di origine da replicare, quindi *Avanti*.
. In Destinazione replica, fornire quanto segue:
+
.. *Nome della destinazione*: il nome della destinazione è stato selezionato in precedenza durante l'operazione di trascinamento e rilascio nella tela.
.. *Nome VM di archiviazione*: seleziona la VM di archiviazione dal menu a discesa.  La VM di archiviazione selezionata è la destinazione per tutti i volumi selezionati in questa relazione di replica.
.. *Nome volume*: il nome del volume di destinazione viene generato automaticamente con il seguente formato `{OriginalVolumeName}_copy` .  È possibile utilizzare il nome del volume generato automaticamente oppure immettere un altro nome del volume.
.. *Caso d'uso*: selezionare uno dei seguenti casi d'uso per la replica.  A seconda del caso d'uso selezionato, Workload Factory compila il modulo con i valori consigliati in conformità con le best practice.  È possibile accettare i valori consigliati o apportare modifiche durante la compilazione del modulo.
+
*** Migrazione: trasferisce i dati al file system FSx for ONTAP di destinazione
*** Ripristino di emergenza a caldo: garantisce elevata disponibilità e rapido ripristino di emergenza per carichi di lavoro critici
*** Ripristino di emergenza a freddo o in archivio:
+
**** Ripristino di emergenza a freddo: utilizza obiettivi di tempo di ripristino (RTO) e oggetti di punto di ripristino (RPO) più lunghi per ridurre i costi
**** Archivio: replica i dati per l'archiviazione a lungo termine e la conformità


*** Altro
+
Inoltre, la selezione del caso d'uso determina la politica di replicazione, o politica SnapMirror (ONTAP).  I termini utilizzati per descrivere le politiche di replicazione provengono dalink:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["Documentazione ONTAP 9"^] .

+
**** Per la migrazione e altro, la politica di replicazione si chiama _MirrorAllSnapshots_.  _MirrorAllSnapshots_ è una policy asincrona per il mirroring di tutti gli snapshot e dell'ultimo file system attivo.
**** Per il disaster recovery a caldo, a freddo o tramite archivio, la policy di replica è denominata _MirrorAndVault_.  _MirrorAndVault_ è una policy asincrona e di vault per il mirroring del file system attivo più recente e degli snapshot giornalieri e settimanali.
+
Per tutti i casi d'uso, se si abilitano gli snapshot per la conservazione a lungo termine, il criterio di replica predefinito è _MirrorAndVault_.





.. *Criterio di suddivisione in livelli*: selezionare il criterio di suddivisione in livelli per i dati archiviati nel volume di destinazione.  Per impostazione predefinita, la politica di suddivisione in livelli è quella consigliata per il caso d'uso selezionato.
+
_Bilanciato (Automatico)_ è il criterio di suddivisione in livelli predefinito quando si crea un volume utilizzando la console Workload Factory.  Per ulteriori informazioni sulle politiche di suddivisione in livelli del volume, fare riferimento alink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacità di archiviazione del volume"^] nella documentazione di AWS FSx per NetApp ONTAP .  Si noti che Workload Factory utilizza nomi basati sui casi d'uso nella console Workload Factory per i criteri di suddivisione in livelli e include i nomi dei criteri di suddivisione in livelli FSx for ONTAP tra parentesi.

+
Se hai selezionato il caso d'uso di migrazione, Workload Factory sceglie automaticamente di copiare la policy di suddivisione in livelli del volume di origine nel volume di destinazione.  È possibile deselezionare la copia del criterio di suddivisione in livelli e selezionare un criterio di suddivisione in livelli che si applichi al volume selezionato per la replica.

.. *Velocità di trasferimento massima*: seleziona *Limitata* e inserisci il limite massimo di trasferimento in MB/s.  In alternativa, seleziona *Illimitato*.
+
Senza limiti, le prestazioni della rete e delle applicazioni potrebbero diminuire.  In alternativa, consigliamo una velocità di trasferimento illimitata per FSx per i file system ONTAP per carichi di lavoro critici, ad esempio quelli utilizzati principalmente per il ripristino di emergenza.



. Nelle impostazioni di replica, specificare quanto segue:
+
.. *Intervallo di replica*: seleziona la frequenza con cui gli snapshot vengono trasferiti dal volume di origine al volume di destinazione.
.. *Conservazione a lungo termine*: facoltativamente, abilitare gli snapshot per la conservazione a lungo termine.  La conservazione a lungo termine consente ai servizi aziendali di continuare a funzionare anche in caso di guasto completo del sito, supportando il failover delle applicazioni in modo trasparente utilizzando una copia secondaria.
+
Le repliche senza conservazione a lungo termine utilizzano il criterio _MirrorAllSnapshots_.  L'abilitazione della conservazione a lungo termine assegna il criterio _MirrorAndVault_ alla replica.

+
Se si abilita la conservazione a lungo termine, selezionare un criterio esistente o crearne uno nuovo per definire gli snapshot da replicare e il numero da conservare.

+

NOTE: Per una conservazione a lungo termine è necessario che le etichette di origine e di destinazione corrispondano.  Se lo desideri, Workload Factory può creare per te le etichette mancanti.

+
*** *Scegli una polizza esistente*: seleziona una polizza esistente dal menu a discesa.
*** *Crea una nuova policy*: inserisci un *nome policy*.


.. *Snapshot immutabili*: Facoltativo.  Selezionare *Abilita snapshot immutabili* per impedire che gli snapshot acquisiti in questo criterio vengano eliminati durante il periodo di conservazione.
+
*** Imposta il *Periodo di conservazione* in numero di ore, giorni, mesi o anni.
*** *Criteri di snapshot*: nella tabella, seleziona la frequenza dei criteri di snapshot e il numero di copie da conservare.  È possibile selezionare più di un criterio snapshot.






. Seleziona *Crea*.




=== Accelerare l'accesso o scaricare il traffico

NetApp Volume Caching fornisce un volume persistente e scrivibile in una posizione remota.  È possibile utilizzare la memorizzazione nella cache dei volumi per velocizzare l'accesso ai dati o per scaricare il traffico dai volumi a cui si accede più frequentemente.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["Introduzione alla memorizzazione nella NetApp Volume Caching"^]
